server:
  port: 8082

spring:
  application:
    name: ticket-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      probes:
        enabled: true

aws:
  region: ${AWS_REGION:eu-west-3}
  endpoint-override: ${AWS_ENDPOINT_OVERRIDE:}
  s3:
    tickets-bucket: ${S3_TICKETS_BUCKET:utopios-tickets-placeholder}

ticket:
  download-ttl-seconds: ${TICKET_TTL_SECONDS:900}