server:
  port: 8080

spring:
  application:
    name: event-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      probes:
        enabled: true