server:
  port: 8081

spring:
  application:
    name: event-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      probes:
        enabled: true

aws:
  region: ${AWS_REGION:eu-west-3}
  endpoint-override: ${AWS_ENDPOINT_OVERRIDE:}
  dynamodb:
    events-table: ${DYNAMODB_EVENTS_TABLE:utopios-events}