apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  namespace: utopios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: utopios/ticket-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: utopios-config
            - secretRef:
                name: aws-credentials
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
  namespace: utopios
spec:
  selector:
    app: ticket-service
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
